server:
  port: 8082
  connectionTimeout: 1S
  tomcat:
    uri-encoding: UTF-8
    max-threads: 0
    max-connections: 0
spring:
  application:
    name: localspringbootdemo
  profiles:
    active: test
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
mybatis:
  config-location: classpath:/mybatis-config.xml
  check-config-location: true

