spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiangtest?useUnicode=true&amp;characterEncoding=UTF-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456

  redis:
    database: 0
    sentinel:
      master: sentinel-10.16.34.125-6423
      nodes: 10.16.34.125:6425,10.16.34.15:6411,10.16.34.16:6399

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  dubbo:
    application:
      name: live-dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
